name: Deploy

on:
  push:
    branches:
      - main

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: ""
          process_type: web

  web:
    name: Web
    runs-on: ubuntu-latest
    needs:
      - api
    steps:
      - name: Build, and Release to GitHub Pages.
        run: |
          GITHUB_TOKEN=$TOKEN
          PAGES_BRANCH="gh-pages"
          GITHUB_HOSTNAME="github.com"
          REPOSITORY=${GITHUB_REPOSITORY}
          git config --global url."https://".insteadOf git://
          git config --global url."$GITHUB_SERVER_URL/".insteadOf "git@${GITHUB_HOSTNAME}":
          remote_repo="https://${GITHUB_TOKEN}@${GITHUB_HOSTNAME}/${REPOSITORY}.git"
          remote_branch=$PAGES_BRANCH
          cd foruma-frontend
          npm ci
          npm run build
          cd dist
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.${GITHUB_HOSTNAME}"
          git add .
          git commit -m "Deploy ${REPOSITORY} to ${REPOSITORY}:$remote_branch"
          git push --force "${remote_repo}" master:${remote_branch}
