name: Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./foruma-frontend

jobs:
  ui-tests:
    name: "UI Tests"
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        id: npm-and-build-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ./foruma-frontend/build
            ./foruma-frontend/node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Cypress Install
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./foruma-frontend
          runTests: false
      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run build

  ui-chrome-tests:
    name: "UI Chrome Tests"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    needs:
      - ui-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        id: npm-and-build-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ./foruma-frontend/build
            ./foruma-frontend/node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./foruma-frontend
          install: false
          start: npm run serve
          wait-on: http://localhost:8080
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: "UI - Chrome"
          spec: "tests/e2e/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:8080
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ui-chrome-mobile-tests:
    name: "UI Chrome Mobile Tests"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    needs:
      - ui-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        id: npm-and-build-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ./foruma-frontend/build
            ./foruma-frontend/node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: "UI Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./foruma-frontend
          install: false
          config: "viewportWidth=375,viewportHeight=667"
          start: npm run serve
          wait-on: http://localhost:8080
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: "UI - Chrome - Mobile"
          spec: "tests/e2e/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:8080
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
